export type AiosCommand =
  | "get_workspace_info"
  | "get_onboarding_state"
  | "save_onboarding_answer"
  | "complete_onboarding"
  | "complete_onboarding_freeform"
  | "reset_onboarding"
  | "reset_workspace"
  | "read_file"
  | "write_file"
  | "append_file"
  | "move_file"
  | "list_modules"
  | "list_skills"
  | "install_module"
  | "get_context_summary"
  | "list_workspace_files"
  | "list_workspace_section"
  | "list_directory"
  | "list_external_directory"
  | "browse_external_directory"
  | "open_external_path"
  | "reveal_external_path"
  | "get_recent_workspace_activity"
  | "read_markdown_preview"
  | "list_outputs"
  | "list_plans"
  | "list_shares"
  | "get_sessions"
  | "create_thread"
  | "rename_thread"
  | "delete_thread"
  | "save_session"
  | "run_prime"
  | "run_task"
  | "transcribe_audio"
  | "get_setting"
  | "set_setting"
  | "find_claude"
  | "set_claude_path"
  | "test_claude_connection"
  | "reveal_in_file_manager"
  | "restore_context_template"
  | "write_binary_file"
  | "list_imports"
  | "delete_import"
  | "toggle_import_marker"
  | "list_marked_import_folders"
  | "link_folder"
  | "unlink_folder"
  | "list_linked_folders"
  | "pick_folder"
  | "list_auto_tasks"
  | "create_auto_task"
  | "update_auto_task"
  | "delete_auto_task"
  | "toggle_auto_task"
  | "list_recent_auto_runs"
  | "list_due_auto_tasks"
  | "begin_auto_task_run"
  | "finish_auto_task_run"
  | "advance_auto_task"
  | "delete_workspace_file"
  | "run_auto_task_now"
  | "get_today_brief_status"
  | "generate_daily_brief"
  | "list_daily_briefs"
  | "mark_brief_seen"
  | "list_import_folder"
  | "create_import_folder"
  | "delete_import_folder"
  | "update_claude_mcp"
  | "rotate_device_user_id"
  | "list_connector_status"
  | "list_agents"
  | "get_agent"
  | "update_agent_prompt"
  | "reset_agent_prompt"
  | "delete_agent"
  | "create_custom_agent"
  | "screen_capture"
  | "screen_ax_tree"
  | "voice_click"
  | "voice_type"
  | "voice_hotkey"
  | "voice_scroll"
  | "voice_move"
  | "voice_open"
  | "voice_drag"
  | "voice_clipboard_get"
  | "voice_clipboard_set"
  | "voice_wait"
  | "voice_check_environment"
  | "voice_get_cursor_type"
  | "mac_check_permissions"
  | "mac_request_permission"
  | "control_panel_toggle"
  | "control_panel_open"
  | "control_panel_close"
  | "control_bubble_toggle"
  | "control_bubble_show"
  | "control_bubble_hide"
  | "control_bubble_drag_start"
  | "control_bubble_drag_to"
  | "control_bubble_drag_end"
  | "control_panel_get_docked"
  | "control_panel_set_docked"
  | "cursor_overlay_get_active"
  | "cursor_overlay_set_active"
  | "cursor_overlay_get_color"
  | "cursor_overlay_set_color"
  | "control_close_all"
  | "control_open_settings"
  | "control_panel_prepare_mic"
  | "control_panel_release_mic"
  | "voice_control_start"
  | "voice_control_stop"
  | "voice_control_abort"
  | "voice_control_state"
  | "goal_start"
  | "goal_abort"
  | "goal_status"
  | "team_start"
  | "team_abort"
  | "team_status"
  | "list_tasks"
  | "get_task"
  | "create_task"
  | "task_action"
  | "cancel_task"
  | "cancel_chat_stream"
  | "delete_task"
  | "whatsapp_status"
  | "whatsapp_start"
  | "whatsapp_stop"
  | "export_to_pdf"
  | "install_claude"
  | "open_claude_login_terminal";

export interface HostRequest {
  id: string;
  cmd: AiosCommand;
  args?: Record<string, unknown>;
}

export interface HostResponse<T = unknown> {
  id: string;
  ok: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
  };
}

export interface HostEvent<T = unknown> {
  id: string;
  event: string;
  data: T;
}

export interface ClaudeDetection {
  found: boolean;
  path: string | null;
  version: string | null;
  checked: string[];
  error?: string;
}
